const mongoose = require('mongoose');

const OrderSchema = new mongoose.Schema({
    orderNo: {
        type: String,
        required: true
    },
    time: {
        type: String,
        required: true
    },
    type:{
        type:String,
        required:true
    },
    currentDepartment:{
        type:String,
        required:true
    },
    clientName:{
        type:String,
        required:true
    },
    redirectionType:{
        type:String,
        required:true
    },
    Notes:{
        type:String,
        required:true
    },
    graphNo:{
        type:String,
        default:false
    },
    requiredColor:{
        type:String,
        default:false
    },
    Dep1:{
        type:Boolean,
        default:false
    },
    Dep2:{
        type:Boolean,
        default:false
    },
    Dep3:{
        type:Boolean,
        rdefault:false
    },
    Dep4:{
        type:Boolean,
        default:false
    },
    Dep5:{
        type:Boolean,
        default:false
    },
    Dep6:{
        type:Boolean,
        default:false
    },
    Dep7:{
        type:Boolean,
        default:false
    },
    Dep8:{
        type:Boolean,
        default:false
    },
    Dep9:{
        type:Boolean,
        default:false
    },
    Dep10:{
        type:Boolean,
        default:false
    },
    Dep11:{
        type:Boolean,
        default:false
    },
    email:{
        type:String,
        default:false
    },
    password:{
        type:String,
        default:false
    },
    visitedDeps:{
        type:String,
        default:false
    },
    Dep1EntryTime:{
        type:String,
        default:false
    },
    Dep1ExitTime:{
        type:String,
        default:false
    },
    Dep2EntryTime:{
        type:String,
        default:false
    },
    Dep2ExitTime:{
        type:String,
        default:false
    },
    Dep3EntryTime:{
        type:String,
        default:false
    },
    Dep3ExitTime:{
        type:String,
        default:false
    },
    Dep4EntryTime:{
        type:String,
        default:false
    },
    Dep4ExitTime:{
        type:String,
        default:false
    },
    Dep5EntryTime:{
        type:String,
        default:false
    },
    Dep5ExitTime:{
        type:String,
        default:false
    },
    Dep6EntryTime:{
        type:String,
        default:false
    },
    Dep6ExitTime:{
        type:String,
        default:false
    },
    Dep7EntryTime:{
        type:String,
        default:false
    },
    Dep7ExitTime:{
        type:String,
        default:false
    },
    Dep8EntryTime:{
        type:String,
        default:false
    },
    Dep8ExitTime:{
        type:String,
        default:false
    },
    Dep9EntryTime:{
        type:String,
        default:false
    },
    Dep9ExitTime:{
        type:String,
        default:false
    },
    Dep10EntryTime:{
        type:String,
        default:false
    },
    Dep10ExitTime:{
        type:String,
        default:false
    },
    Dep11EntryTime:{
        type:String,
        default:false
    },
    Dep11ExitTime:{
        type:String,
        default:false
    },
    DepNo:{
        type:Number,
        default:false
    }
});

const Order = mongoose.model('Order', OrderSchema);

module.exports = Order;